// swift-tools-version: 5.7
import PackageDescription

let package = Package(
    name: "skip-template",
    defaultLocalization: "en",
    products: [
        .library(name: "TemplateLib", targets: ["TemplateLib"]),
    ],
    targets: [
        .target(name: "TemplateLib"),
        .testTarget(name: "TemplateLibTests", dependencies: [
            "TemplateLib",
        ]),
    ]
)

package.dependencies += [.package(url: "https://github.com/skiptools/skip.git", from: "0.0.0")]
package.dependencies += [.package(url: "https://github.com/skiptools/skiphub.git", from: "0.0.0")]

// MARK: SKIP TARGETS

// Everything after this line will be re-generated by the Skip plug-in

package.products += [
    .library(name: "TemplateLibKt", targets: ["TemplateLibKt"])
]

package.targets += [
    .target(name: "TemplateLibKt", dependencies: [
        "TemplateLib",
        .product(name: "SkipFoundationKt", package: "skiphub"),
    ],
            resources: [.copy("skip")],
            plugins: [.plugin(name: "transpile", package: "skip")])
]

package.targets += [
    .testTarget(name: "TemplateLibTestsKt", dependencies: [
        "TemplateLibKt",
        .product(name: "SkipUnit", package: "skiphub"),
        .product(name: "SkipUnitKt", package: "skiphub"),
    ],
                resources: [.copy("skip")],
                plugins: [.plugin(name: "transpile", package: "skip")])
]


import class Foundation.ProcessInfo
// For Skip library development in peer directories, run: SKIPLOCAL=.. xed Package.swift
if let localPath = ProcessInfo.processInfo.environment["SKIPLOCAL"] {
    // locally linking SwiftSyntax requires explicit min platform targets
    package.platforms = package.platforms ?? [.iOS(.v15), .macOS(.v12), .tvOS(.v15), .watchOS(.v8), .macCatalyst(.v15)]
    package.dependencies[package.dependencies.count - 2] = .package(path: localPath + "/skip")
    package.dependencies[package.dependencies.count - 1] = .package(path: localPath + "/skiphub")
}
